–ûÀY<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:4772;s:11:"post_author";s:1:"1";s:9:"post_date";s:19:"2014-09-01 11:32:02";s:13:"post_date_gmt";s:19:"2014-09-01 11:32:02";s:12:"post_content";s:3289:"[mk_page_section bg_image="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/09/contact-02-bg.jpg" attachment="fixed" bg_stretch="true" min_height="0" full_height="true" sidebar="sidebar-1" first_page="false" last_page="false"][vc_column][mk_fancy_title color="#ffffff" size="28" font_weight="bold" font_style="inhert" txt_transform="uppercase" letter_spacing="6" margin_bottom="0" font_family="none" align="center"]Florence[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="30" thickness="3" margin_top="30" margin_bottom="30"][vc_column_text disable_pattern="false" align="center" margin_bottom="60"]
<p style="color: white; line-height: 32px; font-size: 16px; letter-spacing: 1px;">Patricia C. Amedee 4401
Waldeck Street Grapevine
Nashville, TX 76051
Email: email@yourdomain.com
Phone: +99 (0) 101 0000 888
Fax: +99 (0) 800 0000 008</p>
[/vc_column_text][vc_row_inner attached="true"][vc_column_inner width="1/4"][/vc_column_inner][vc_column_inner width="1/4"][mk_button dimension="outline" corner_style="rounded" size="large" url="#map" align="right" outline_skin="light"]DIRECTIONS[/mk_button][/vc_column_inner][vc_column_inner width="1/4"][mk_button dimension="outline" corner_style="rounded" size="large" url="#msg" outline_skin="light"]SEND MESSAGE[/mk_button][/vc_column_inner][vc_column_inner width="1/4"][/vc_column_inner][/vc_row_inner][/vc_column][/mk_page_section][mk_page_section bg_color="#292a2d" min_height="0" full_height="true" padding_top="60" padding_bottom="60" section_id="msg" sidebar="sidebar-1" first_page="false" last_page="false"][vc_column][mk_fancy_title color="#ffffff" size="20" font_weight="bold" font_style="inhert" txt_transform="uppercase" letter_spacing="2" margin_bottom="0" font_family="none" align="center"]WRITE TO US[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="30" thickness="3" margin_top="30" margin_bottom="30"][vc_row_inner][vc_column_inner width="1/4"][/vc_column_inner][vc_column_inner width="1/2"][vc_column_text disable_pattern="false" align="center" margin_bottom="60"]
<p style="color: #898989;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum, lectus in dapibus molestie, quam felis sollicitudin mauris, sit amet tempus velit lectus nec lorem. Nullam vel mollis neque.</p>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/4"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][mk_contact_form skin="light"][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/mk_page_section][vc_row fullwidth="true" padding="0" id="map"][vc_column][mk_advanced_gmaps latitude="40.748829" longitude="-73.984118" address="Patricia C. Amedee 4401 Waldeck Street Grapevine Nashville, TX 76051" latitude_2="40.743920" longitude_2="-74.003945" address_2="Patricia C. Amedee 4401 Waldeck Street Grapevine Nashville, TX 76051" pin_icon="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/google-map-icon.png" map_height="full" draggable="false" modify_coloring="true" hue="#878787" saturation="-100" parallax="false"][/vc_column][/vc_row]";s:10:"post_title";s:13:"Contact Fancy";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:4:"open";s:11:"ping_status";s:4:"open";s:13:"post_password";s:0:"";s:9:"post_name";s:13:"contact-fancy";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2014-09-01 11:32:02";s:17:"post_modified_gmt";s:19:"2014-09-01 11:32:02";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:4739;s:4:"guid";s:47:"http://demos.artbees.net/jupiter5/?page_id=4772";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}