–ûÀY<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:3369;s:11:"post_author";s:1:"1";s:9:"post_date";s:19:"2014-08-22 14:49:43";s:13:"post_date_gmt";s:19:"2014-08-22 14:49:43";s:12:"post_content";s:7176:"[vc_row][vc_column width="1/1"][mk_fancy_title tag_name="h2" style="false" color="#333333" size="24" font_weight="bold" txt_transform="uppercase" letter_spacing="1" margin_top="40" margin_bottom="0" align="center"]Revolutionary custom box is here.[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="25" align="center" border_color="#f97352" thickness="3" margin_top="15" margin_bottom="35"][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][vc_column_text disable_pattern="false" align="center" margin_bottom="0"]<span style="color: #6e6e6e; font-size: 16px;">Now you can create your own box or banner from scratch and display anything inside. No limit. You can even insert in multiple columns.</span>[/vc_column_text][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row fullwidth="true" attached="false" padding="0"][vc_column width="1/1"][mk_divider divider_width="full_width" custom_width="10" align="center" border_color="#ebebeb" thickness="1" margin_top="30" margin_bottom="30" style="thin_solid"][/vc_column][/vc_row][vc_row][vc_column width="1/3"][mk_custom_box border_color="#eaeaea" bg_color="#f97352" padding_vertical="30" padding_horizental="40" margin_bottom="50" min_height="100" width="1/1" el_position="first last" bg_position="left top" bg_repeat="repeat" bg_stretch="false" border_width="1"][vc_row_inner][vc_column_inner width="1/1"][mk_fancy_title tag_name="h1" style="false" color="#ffffff" size="20" font_weight="bold" margin_top="0" margin_bottom="10" font_family="none" align="center" width="1/1" el_position="first last"]Column 1[/mk_fancy_title][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="0" width="1/1" el_position="first last"]
<p style="text-align: center;"><span style="color: #ffffff;">Praesent mi risus, fringilla et congue a, adipiscing a justo. Etiam non nulla libero. Proin vitae feugiat ante. In semper dignissim rutrum. Vestibulum ante ipsum.</span></p>
[/vc_column_text][mk_button dimension="outline" size="medium" bg_color="#00b89a" text_color="light" icon="icon-arrow-right" target="_self" align="center" margin_top="30" margin_bottom="15" width="1/1" el_position="first last" outline_button_color="#666666" outline_txt_color="#666666" outline_txt_hover_color="#ffffff" outline_skin="light" outline_active_color="#ffffff" outline_hover_color="#333333" fullwidth="false" corner_style="pointed" btn_hover_bg="#252525" icon_anim="none"]CLICK HERE

[/mk_button][/vc_column_inner][/vc_row_inner][/mk_custom_box][/vc_column][vc_column width="1/3"][mk_custom_box border_color="#eaeaea" bg_color="#f6f6f6" predefined_bg="22" padding_vertical="30" padding_horizental="40" margin_bottom="50" min_height="100" width="1/1" el_position="first last" bg_position="left top" bg_repeat="repeat" bg_stretch="false" border_width="1"][vc_row_inner][vc_column_inner width="1/1"][mk_fancy_title tag_name="h1" style="false" color="#333333" size="20" font_weight="bold" margin_top="0" margin_bottom="10" align="center" width="1/1" el_position="first last" letter_spacing="0"]Column 2[/mk_fancy_title][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="0" width="1/1" el_position="first last"]
<p style="text-align: center;"><span style="color: #333333;">Praesent mi risus, fringilla et congue a, adipiscing a justo. Etiam non nulla libero. Proin vitae feugiat ante. In semper dignissim rutrum. Vestibulum ante ipsum.</span></p>
[/vc_column_text][mk_button dimension="outline" size="medium" bg_color="#00b89a" text_color="light" icon="icon-arrow-right" target="_self" align="center" margin_top="30" margin_bottom="15" width="1/1" el_position="first last" outline_button_color="#666666" outline_txt_color="#666666" outline_txt_hover_color="#ffffff" outline_skin="dark" outline_active_color="#ffffff" outline_hover_color="#333333" fullwidth="false" corner_style="pointed" btn_hover_bg="#252525" icon_anim="none"]CLICK HERE

[/mk_button][/vc_column_inner][/vc_row_inner][/mk_custom_box][/vc_column][vc_column width="1/3"][mk_custom_box border_color="#eaeaea" bg_color="#f6f6f6" predefined_bg="9" padding_vertical="30" padding_horizental="40" margin_bottom="50" min_height="100" width="1/1" el_position="first last" bg_position="center center" bg_repeat="no-repeat" bg_stretch="true" bg_image="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/custom-box-bg-01.jpg" border_width="1"][vc_row_inner][vc_column_inner width="1/1"][mk_fancy_title tag_name="h1" style="false" color="#ffffff" size="20" font_weight="bold" margin_top="0" margin_bottom="10" font_family="none" align="center" width="1/1" el_position="first last"]Column 3[/mk_fancy_title][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="0" width="1/1" el_position="first last"]
<p style="text-align: center;"><span style="color: #ffffff;">Praesent mi risus, fringilla et congue a, adipiscing a justo. Etiam non nulla libero. Proin vitae feugiat ante. In semper dignissim rutrum. Vestibulum ante ipsum.</span></p>
[/vc_column_text][mk_button dimension="outline" size="medium" bg_color="#00b89a" text_color="light" icon="icon-arrow-right" target="_self" align="center" margin_top="30" margin_bottom="15" width="1/1" el_position="first last" outline_button_color="#666666" outline_txt_color="#666666" outline_txt_hover_color="#ffffff" outline_skin="light" outline_active_color="#ffffff" outline_hover_color="#333333" fullwidth="false" corner_style="pointed" btn_hover_bg="#252525" icon_anim="none"]CLICK HERE

[/mk_button][/vc_column_inner][/vc_row_inner][/mk_custom_box][/vc_column][/vc_row][vc_row][vc_column width="1/1"][mk_custom_box border_color="#eaeaea" bg_color="#f6f6f6" padding_vertical="40" padding_horizental="40" margin_bottom="50" min_height="100" width="1/1" el_position="first last"][vc_row_inner][vc_column_inner width="2/3"][mk_fancy_title tag_name="h1" style="false" color="#666666" size="28" font_weight="300" margin_top="0" margin_bottom="20" font_family="Oswald" font_type="google" align="left" width="1/1" el_position="first last"]

Why use custom box?

[/mk_fancy_title][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="0" width="1/1" el_position="first"]Praesent mi risus, fringilla et congue a, adipiscing a justo. Etiam non nulla libero. Proin vitae feugiat ante. In semper dignissim rutrum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Ut vitae nulla in dui ullamcorper molestie ac at eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.Â <span style="color: #252525;">Vestibulum ante ipsum primis in faucibus orci luctus.</span>[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][mk_laptop_slideshow images="3347,3346" size="one-third" animation_speed="700" slideshow_speed="7000" pause_on_hover="false" width="1/1" el_position="last"][/vc_column_inner][/vc_row_inner][/mk_custom_box][/vc_column][/vc_row][vc_row][vc_column width="1/1"][mk_padding_divider size="60"][/vc_column][/vc_row]";s:10:"post_title";s:13:"Custom box 33";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:4:"open";s:11:"ping_status";s:6:"closed";s:13:"post_password";s:0:"";s:9:"post_name";s:21:"custom-callout-box-33";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2014-08-22 14:49:43";s:17:"post_modified_gmt";s:19:"2014-08-22 14:49:43";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:395;s:4:"guid";s:47:"http://demos.artbees.net/jupiter5/?page_id=3369";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}