–ûÀY<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:397;s:11:"post_author";s:1:"1";s:9:"post_date";s:19:"2014-08-22 08:31:32";s:13:"post_date_gmt";s:19:"2014-08-22 08:31:32";s:12:"post_content";s:18029:"[vc_row][vc_column width="1/1"][mk_fancy_title tag_name="h2" style="false" color="#333333" size="24" font_weight="bold" txt_transform="uppercase" letter_spacing="2" margin_top="0" margin_bottom="0" align="center"]Fancy style[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="25" align="center" border_color="#f97352" thickness="3" margin_top="15" margin_bottom="35"][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][vc_column_text disable_pattern="false" align="center" margin_bottom="60"]You can choose between 2 styles according to your website look and feel. There are also 3 types of Actions: One section, multiple sections or a specific section open at a time.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column width="2/3"][vc_accordions style="fancy-style" action_style="accordion-action" open_toggle="-1" container_bg_color="#ffffff" width="2/3" el_position="first"][vc_accordion_tab icon="moon-images-2" title="Amazing sliders"][vc_row_inner][vc_column_inner width="1/2" el_position="first"][mk_image src="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/misc-8.jpg" image_width="250" image_height="200" lightbox="false" frame_style="simple" caption_location="inside-image" align="left" width="1/1" el_position="first last"][/vc_column_inner][vc_column_inner width="1/2" el_position="last"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_accordion_tab][vc_accordion_tab icon="moon-paint-format-2" title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab icon="icon-bolt" title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][vc_column width="1/3"][vc_accordions style="fancy-style" action_style="accordion-action" open_toggle="-1" container_bg_color="#ffffff" width="1/3" el_position="last"][vc_accordion_tab title="Amazing sliders"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][/vc_row][vc_row][vc_column width="1/1"][mk_fancy_title tag_name="h1" style="true" color="#393836" size="14" font_weight="inhert" margin_top="30" margin_bottom="25" font_family="none" align="left" width="1/1" el_position="first last"]

Multiple toggle open at a time

[/mk_fancy_title][/vc_column][/vc_row][vc_row][vc_column width="1/3"][vc_accordions style="fancy-style" action_style="toggle-action" open_toggle="-1" container_bg_color="#ffffff" width="1/3" el_position="first"][vc_accordion_tab icon="moon-images-2" title="Amazing sliders"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][vc_column width="2/3"][vc_accordions style="fancy-style" action_style="toggle-action" open_toggle="3" container_bg_color="#ffffff" width="2/3" el_position="last"][vc_accordion_tab icon="moon-images-2" title="Amazing sliders"][vc_row_inner][vc_column_inner width="1/2" el_position="first"][mk_image src="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/misc-8.jpg" image_width="250" image_height="200" lightbox="false" frame_style="simple" caption_location="inside-image" align="left" width="1/1" el_position="first last"][/vc_column_inner][vc_column_inner width="1/2" el_position="last"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_accordion_tab][vc_accordion_tab icon="moon-paint-format-2" title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab icon="icon-bolt" title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][/vc_row][vc_row][vc_column width="1/1"][mk_fancy_title tag_name="h1" style="true" color="#393836" size="14" font_weight="inhert" margin_top="30" margin_bottom="25" font_family="none" align="left" width="1/1" el_position="first last"]

One toggle open by default specified by user

[/mk_fancy_title][/vc_column][/vc_row][vc_row][vc_column width="2/3"][vc_accordions style="fancy-style" action_style="accordion-action" open_toggle="0" container_bg_color="#ffffff" width="2/3" el_position="first"][vc_accordion_tab icon="moon-images-2" title="Amazing sliders"][vc_row_inner][vc_column_inner width="1/2" el_position="first"][mk_image src="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/misc-8.jpg" image_width="250" image_height="200" lightbox="false" frame_style="simple" caption_location="inside-image" align="left" width="1/1" el_position="first last"][/vc_column_inner][vc_column_inner width="1/2" el_position="last"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_accordion_tab][vc_accordion_tab icon="moon-paint-format-2" title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab icon="icon-bolt" title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][vc_column width="1/3"][vc_accordions style="fancy-style" action_style="accordion-action" open_toggle="2" container_bg_color="#ffffff" width="1/3" el_position="last"][vc_accordion_tab icon="moon-images-2" title="Amazing sliders"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][/vc_row][vc_row][vc_column width="1/1"][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row fullwidth="true" attached="false" padding="0"][vc_column width="1/1"][mk_divider style="thin_solid" divider_width="full_width" margin_top="60" margin_bottom="50" width="1/1" el_position="first last" custom_width="10" align="center" border_color="#dadada" thickness="1"][/vc_column][/vc_row][vc_row][vc_column width="1/1"][mk_fancy_title tag_name="h2" style="false" color="#333333" size="24" font_weight="bold" txt_transform="uppercase" letter_spacing="2" margin_top="0" margin_bottom="0" align="center"]SimpleÂ style[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="25" align="center" border_color="#f97352" thickness="3" margin_top="15" margin_bottom="35"][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][vc_column_text disable_pattern="false" align="center" margin_bottom="60"]You can choose between 2 styles according to your website look and feel. There are also 3 types of Actions: One section, multiple sections or a specific section open at a time.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column width="2/3"][mk_fancy_title tag_name="h1" style="true" color="#393836" size="14" font_weight="inhert" margin_top="0" margin_bottom="25" font_family="none" align="left" width="1/1" el_position="first"]

One toggle open at a time

[/mk_fancy_title][vc_accordions style="simple-style" action_style="accordion-action" open_toggle="-1" container_bg_color="#ffffff" width="2/3" el_position="first"][vc_accordion_tab icon="moon-images-2" title="Amazing sliders"][vc_row_inner][vc_column_inner width="1/2" el_position="first"][mk_image src="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/misc-8.jpg" image_width="250" image_height="200" lightbox="false" frame_style="simple" caption_location="inside-image" align="left" width="1/1" el_position="first last"][/vc_column_inner][vc_column_inner width="1/2" el_position="last"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_accordion_tab][vc_accordion_tab icon="moon-paint-format-2" title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab icon="icon-bolt" title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][vc_column width="1/3"][mk_fancy_title tag_name="h1" style="true" color="#393836" size="14" font_weight="inhert" margin_top="0" margin_bottom="25" font_family="none" align="left" width="1/1" el_position="last"]

Multiple toggle open at a time

[/mk_fancy_title][vc_accordions style="simple-style" action_style="toggle-action" open_toggle="-1" container_bg_color="#ffffff" width="1/3" el_position="last"][vc_accordion_tab icon="moon-images-2" title="Amazing sliders"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab icon="moon-paint-format-2" title="Unlimited colors"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][vc_accordion_tab icon="icon-bolt" title="Tons of shortcodes"][vc_column_text disable_pattern="true" align="left" margin_bottom="0" p_margin_bottom="20" width="1/1" el_position="first last"]
<div>Fugiat dapibus, tellus ac cursus commodo, mauris sit condim eser ntumsi nibh, uum a justo vitaes amet risus amets un. Posi sectetut amet fermntum orem ipsum quia dolor sit amet, consectetur, adipisci velit, <strong>sed quia nons</strong>.</div>
[/vc_column_text][/vc_accordion_tab][/vc_accordions][/vc_column][/vc_row][vc_row][vc_column width="1/1"][mk_padding_divider size="50"][/vc_column][/vc_row]";s:10:"post_title";s:21:"Accordion and Toggles";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:4:"open";s:11:"ping_status";s:4:"open";s:13:"post_password";s:0:"";s:9:"post_name";s:21:"accordion-and-toggles";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2014-08-22 08:31:32";s:17:"post_modified_gmt";s:19:"2014-08-22 08:31:32";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:395;s:4:"guid";s:46:"http://demos.artbees.net/jupiter5/?page_id=397";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}