���Y<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:5643;s:11:"post_author";s:1:"1";s:9:"post_date";s:19:"2015-06-10 09:49:45";s:13:"post_date_gmt";s:19:"2015-06-10 09:49:45";s:12:"post_content";s:13288:"[mk_page_section bg_image="https://giqk9lga.dreamwp.com/wp-content/uploads/2015/06/pexels-photo-29672-large.jpg" bg_stretch="true" video_color_mask="#000000" min_height="794" full_width="true" full_height="true" intro_effect="fade" section_id="bannerimg" sidebar="sidebar-1"][vc_column][mk_fancy_title color="#ffffff" size="42" font_weight="bold" font_family="none" align="center"]ABOUT US[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="30" thin_single_color="#f05d27"][vc_row_inner][vc_column_inner width="1/3"][/vc_column_inner][vc_column_inner width="1/3"][mk_fancy_title color="#ffffff" size="24" letter_spacing="1" font_family="none" align="center"]We have a genuine and invested interest in helping our clients succeed.[/mk_fancy_title][/vc_column_inner][vc_column_inner width="1/3"][/vc_column_inner][/vc_row_inner][/vc_column][/mk_page_section][mk_page_section section_id="aboutusdetails" animation="bottom-to-top" sidebar="sidebar-1"][vc_column][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][mk_fancy_title tag_name="span" color="#f05d27" size="28" txt_transform="capitalize" letter_spacing="1" margin_top="120" margin_bottom="0" font_family="Montserrat" font_type="google" align="center" animation="bottom-to-top"]INDUSTRY LEADER IN APP DESIGN AND DEVELOPMENT.[/mk_fancy_title][mk_blockquote style="line-style" font_family="none"]We are solution providers. We listen to our clients, embrace their vision and focus on providing the best technical solutions that will result in immersive, smooth user experiences.[/mk_blockquote][mk_blockquote style="line-style" font_family="none"]With a vision of the future of mobile app technology, App Gurus know what works, how it works and why it works.[/mk_blockquote][vc_column_text disable_pattern="false" align="center" animation="bottom-to-top"]
<div style="color: #808080; font-size: 16px;"></div>
<h4 style="color: #808080; font-size: 20px;">We design with purpose and innovate with direction.</h4>
[/vc_column_text][mk_padding_divider size="80"][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][vc_row_inner animation="bottom-to-top"][vc_column_inner width="1/2"][mk_title_box color="#f05d27" size="24" font_family="none" align="center" animation="left-to-right"]WHAT WE DO?[/mk_title_box][vc_column_text animation="fade-in"]
<p style="text-align: justify;">We work with individuals, businesses, companies and entrepreneurs to execute ideas into successful concepts. We design and build mobile apps, web based systems, prototypes and advise our clients on the most ideal solutions for builds of future proof and scale-able infrastructure.</p>
<p style="text-align: justify;">We have a team of gurus in every department ranging across design, technical analyst, programming experts for various platforms and marketing professionals utilizing the latest industry tech tools to deliver projects within world class standards.</p>
<p style="text-align: justify;">As leaders in a forever rapidly evolving industry, our core focus is on delivering solutions for our clients to discover, grow and expand their business opportunities in the app space.[/vc_column_text][mk_button dimension="outline" size="large" url="https://giqk9lga.dreamwp.com/services/" margin_top="10" margin_bottom="0" margin_right="0" animation="left-to-right" outline_skin="custom" outline_active_color="#f05d27" outline_active_text_color="#f05d27" outline_hover_bg_color="#f05d27" outline_hover_color="#ffffff"]Our Services[/mk_button][/vc_column_inner][vc_column_inner width="1/2"][mk_title_box color="#f05d27" size="24" font_family="none" align="center" animation="right-to-left"]DESIGN &amp; DEVELOPMENT[/mk_title_box][vc_column_text animation="fade-in"]</p>
<p style="text-align: justify;">From design to execution, we engage with our clients to understand their needs and behaviours of their target audience to deliver a world class <strong>User Interface (UI)</strong> and <strong>User Experience (UX)</strong>. Every app has a unique identity and purpose, therefore is customised to align seamlessly with the user.</p>
<p style="text-align: justify;">First we design your app/web platform. The colours, branding, styling, navigational structure, all of it. You physically see it. Then we build it. We have rigid processes in place to ensure projects meet top industry standards across all stages of production.</p>
Visit our portfolio to preview of some of our work.[/vc_column_text][mk_button dimension="outline" size="large" url="https://giqk9lga.dreamwp.com/portfolio-01/" margin_top="10" margin_bottom="0" margin_right="0" animation="left-to-right" outline_skin="custom" outline_active_color="#f05d27" outline_active_text_color="#f05d27" outline_hover_bg_color="#f05d27" outline_hover_color="#ffffff"]Portfolio [/mk_button][/vc_column_inner][/vc_row_inner][/vc_column][/mk_page_section][vc_row padding="0"][vc_column][mk_padding_divider size="80"][/vc_column][/vc_row][vc_row][vc_column][/vc_column][/vc_row][vc_row padding="0"][vc_column width="1/6"][/vc_column][vc_column width="2/3"][mk_padding_divider][mk_fancy_title color="#f05d27" size="48" txt_transform="capitalize" letter_spacing="1" margin_bottom="40" font_family="Montserrat" font_type="google" align="center" animation="flip-y"]OUR DEVELOPMENT PROCESS[/mk_fancy_title][vc_column_text disable_pattern="false" align="center" animation="bottom-to-top"]We use a development life-cycle composed of a number of clearly defined work phases to analyse, design, develop, test and launch your project.

Our adoption of the latest trends is paramount in delivering high performance solutions to our clients.[/vc_column_text][mk_padding_divider][/vc_column][vc_column width="1/6"][/vc_column][vc_column][/vc_column][/vc_row][vc_row][vc_column][vc_tta_pageable no_fill_content_area="1" autoplay="5" active_section="1" css_animation="fadeInRightBig"][vc_tta_section title="Section 1" tab_id="1490874003398-8cd25759-7d30"][mk_fancy_title tag_name="h4" color="#f05d27" font_family="none" animation="right-to-left"]
<h4>CONCEPT &amp; DESIGN</h4>
[/mk_fancy_title][vc_column_text animation="bottom-to-top"]Getting the visual architecture right is a critical step in delivering a great <strong>User Experience (UX)</strong>. We initiate this phase by mapping out the navigational structure and screen layout, generally known as the wire-frame. Wire-frames validate the usability of an application by allowing the user the visualise and navigate through all the sections. During this process we prepare strategic arrangement of elements throughout the entire application. Based on the wire-frame we initiate the branding and design to deliver what will be the visual masterpiece of the application every user will see when they use the application.[/vc_column_text][/vc_tta_section][vc_tta_section title="Section 2" tab_id="1490874003496-4f4a0752-8ffc"][mk_fancy_title tag_name="h4" color="#f05d27" font_family="none" animation="right-to-left"]
<h4>DEVELOPMENT</h4>
[/mk_fancy_title][vc_column_text animation="bottom-to-top"]Design slicing and integration into the user interface is the first step of the development stage. Engaging in extensive hours of programming our developers strategically formulate the functional parameters of the application and database structure. During development, you will have a direct and open line of communication with your project manager who will keep you up to date with the progression of your project.[/vc_column_text][mk_button dimension="outline" corner_style="rounded" size="medium" url="https://giqk9lga.dreamwp.com/contact-us/" margin_top="10" margin_bottom="0" margin_right="0" outline_skin="custom" outline_active_color="#f05d27" outline_active_text_color="#f05d27" outline_hover_bg_color="#f05d27" outline_hover_color="#ffffff"]Enquire Now[/mk_button][/vc_tta_section][vc_tta_section title="Section 3" tab_id="1490874263780-5bb9fd8c-498b"][mk_fancy_title tag_name="h4" color="#f05d27" font_family="none" animation="right-to-left"]
<h4>TESTING &amp; LAUNCH</h4>
[/mk_fancy_title][vc_column_text animation="bottom-to-top"]Your project is tested internally at progressive intervals. We do in-depth assessment on the usability, functionality, performance, security and device compatibility to ensure you receive a bug-free application ready to rock the marketplace. You will also receive a a range of BETA versions to test on your device(s) before the launch. This way we make sure your app is at 100% upon final delivery.

We guide you with the entire process of what is required to have the application published in the Apple App Store and Google Play Store globally.

If your platform is for private business/company use, then we do not launch your app into the app stores.[/vc_column_text][/vc_tta_section][/vc_tta_pageable][/vc_column][/vc_row][mk_page_section bg_color="#f6f6f6" border_color="rgba(0,0,0,0.3)" attachment="fixed" bg_position="center center" bg_repeat="no-repeat" bg_stretch="true" enable_3d="true" top_shadow="true" min_height="0" padding_top="80" padding_bottom="60" first_page="false" last_page="false" sidebar="sidebar-1"][vc_column][mk_fancy_title color="#f05d27" size="48" txt_transform="capitalize" letter_spacing="1" margin_bottom="40" font_family="Montserrat" font_type="google" align="center"]MEET THE FOUNDERS[/mk_fancy_title][vc_row_inner][vc_column_inner width="1/4"][vc_icon icon_fontawesome="fa fa-spinner" color="custom" size="lg" align="center" custom_color="#f05d27"][mk_fancy_title font_family="none" align="center" animation="left-to-right"]
<h3>Ben Bradshaw</h3>
<h5>Co-Founder</h5>
[/mk_fancy_title][/vc_column_inner][vc_column_inner width="3/4"][vc_column_text animation="right-to-left"]
<p style="text-align: justify;">Ben Bradshaw is one of Australia’s most established, renowned &amp; respected internet pioneers. As testament to his enormous success, Ben is now a self-made millionaire, an author, and winner of Smart Company’s Hot 30 Australian entrepreneurs under 30, among many other prestigious buisness awards. Ben’s entrepreneurial approach and knowledge on Internet marketing resulted in his first major internet marketing business SponsoredLinX, doubling its revenue year on year since its inception, and earning its place as one of the country’s most highly regarded and fastest growing Search Marketing companies.</p>
<p style="text-align: justify;">Just after its inception, SponsoredLinX quickly made significant waves in the industry and was approached to become one of only a very select few authorised Google resellers resulting it in now being a Premier Google Partner – one of a small prestigious group of companies handpicked by Google. Ben’s hunger for achievement didn’t only become apparent as he entered adulthood. He in fact started his first business at age 14 – corporate magic – and quickly became one of Australia’s most popular magicians, with his career highlight being the Guinness World Record for the fastest escape from a straight jacket! An expert columnist on multiple international and US Internet marketing specialist print and online publications, Ben is also regularly quoted on Internet marketing topics locally on Sky Business, in business publications like Smart Company and BRW, and in major metropolitan newspapers. Ben is one of Australia’s most sought-after and respected speakers and trainers on marketing and internet entrepreneurship.[/vc_column_text][vc_column_text][/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/4"][vc_empty_space][vc_icon icon_fontawesome="fa fa-spinner" color="custom" size="lg" align="center" custom_color="#f05d27"][mk_fancy_title font_family="none" align="center" animation="left-to-right"]</p>

<h3>Mathew Carter</h3>
<h5>Co-Founder &amp; Technical Manager</h5>
[/mk_fancy_title][/vc_column_inner][vc_column_inner width="3/4"][vc_empty_space][vc_column_text animation="right-to-left"]
<p style="text-align: justify;">Mathew Carter met Ben when he was working in a Brisbane web firm when Ben was just starting out in the online marketing industry. He originally consulted with Ben on a number of projects and this was when Ben first recognised Mathew’s talent. A time later, while Mathew was still in university, he was approached by Ben to consult and work on the initial set up for SponsoredLinX, which is now Australia’s largest Australian owned search engine marketing company.</p>
<p style="text-align: justify;">Mathew has been the backbone of the systems implementation at SponsoredLinX for over 7 years and has maintained systems such as; client invoice &amp; billing, client management panel and many other internal systems and operations.</p>
<p style="text-align: justify;">Through this role Mathew has learned a great deal about how to practically implement his vast knowledge of programming and systems management. Being a key contributor in a highly accredited and successfully company, Mathew has learnt what helps businesses to succeed in the online and tech space and now the rapidly growing mobile app evolution.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/mk_page_section]</p>";s:10:"post_title";s:8:"About Us";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:4:"open";s:11:"ping_status";s:4:"open";s:13:"post_password";s:0:"";s:9:"post_name";s:8:"about-us";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2017-09-18 13:59:54";s:17:"post_modified_gmt";s:19:"2017-09-18 03:59:54";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:0;s:4:"guid";s:50:"http://demos.artbees.net/jupiter5/thebe/?page_id=7";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}