<?php
/**
* Header file for the Twenty Twenty WordPress default theme.
*
* @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
*
* @package WordPress
* @subpackage Twenty_Twenty
* @since Twenty Twenty 1.0
*/
?>
<!DOCTYPE html>

<html class="no-js" <?php language_attributes(); ?>>

<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-77173647-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  _gaq.push(['_setAccount', 'UA-77173647-1']);
  _gaq.push(['_trackPageview']);
  gtag('config', 'UA-77173647-1');
</script>  -->

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7CPB7RZ1MZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7CPB7RZ1MZ');
</script>

<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "h9bz1n0be4");
</script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NZN73T5');</script>
<!-- End Google Tag Manager -->

<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"187071745"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>

<script type="text/javascript">
    var ajaxurl = "<?php echo admin_url('admin-ajax.php'); ?>";
</script>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="google-site-verification" content="5Au7RwZpnetIiB9AJIrDhPnZcLsvS2uieKOr4_r5kAs" />
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

<?php wp_head(); ?>

<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '473131272865502');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=473131272865502&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
<?php

global $wp_query;
$post_id = $wp_query->post->ID;

$post = get_post( $post_id );
$slug = $post->post_name;

?>
</head>

<body <?php body_class(); ?>>

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NZN73T5"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<?php
wp_body_open();

if (!is_page_template( 'templates/thankyou-page.php' ))
{ 
?>
<div class="page-wrapper"> 
	<!-- loader start -->
	<!-- <div id="preloader" class="preloader-circle">
      <div class="img-sec">
        <img src="<?php //bloginfo('template_directory'); ?>/images/loader-logo.png" alt="AppGurus"> <span class="brandname">app<span style="color: #414042;">gurus</span></span>
      </div>
      
        <div class="circle-loader" >
          
        </div> 
    </div> -->
    <!-- loader end -->
<header>

<div class="header-main" id="myHeader">
  <div class="container">
    <nav class="navbar navbar-dark navbar-expand-lg">
      <div class="header-inner d-flex align-items-center">
        <div class="header-left">
          <div class="header-logo">
          <a href="<?php echo esc_url( home_url( '/' ) ); ?>">  <img src="<?php bloginfo('template_directory'); ?>/images/Logo/header-logo.png" alt="logo"> </a>
          </div>
        </div>
        <div class="header-right">
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>

          <div class="collapse header-menu navbar-collapse justify-content-end" id="navbarNav">
            <div class="header-menu-inner">
              <?php //wp_nav_menu( array( 'menu' => 'Top Navigation', 'container_class' => '', 'container_id' => '',  'items_wrap' => '<ul class="navbar-nav">%3$s'  ) );?>
                <ul class="navbar-nav">
                    <li class="nav-item <?php echo ($slug == 'home')?'active':''; ?>">
                      <a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a>
                    </li>
                    <li class="nav-item <?php echo ($slug == 'about-app-development-australia')?'active':''; ?>">
                      <a href="<?php echo esc_url( home_url( 'about-app-development-australia/' ) ); ?>">About Us </a>
                    </li>
                    <li class="nav-item <?php echo ($slug == 'portfolio-app-development-company-australia')?'active':''; ?>">
                      <a href="<?php echo esc_url( home_url( 'portfolio-app-development-company-australia/' ) ); ?>">Portfolio</a>
                    </li>
                  
                    <?php
                    $servicePages = array('digital-services-australia','flutter-app-development-brisbane-australia');
                    ?>
                    
                    <li class="nav-item check1 <?php echo in_array($slug, $servicePages) ? 'active' : ''; ?>">
                      <div class="main-menu" id="menu_heading1">
                         <a href="<?php echo site_url( '/digital-services-australia/'); ?>">Services</a>
                         <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                           data-target="#smenu_collapse1" aria-expanded="false" aria-controls="smenu_collapse1">
                           <i class="fa fa-angle-down"></i>
                         </button>
                      </div>
                      <div id="smenu_collapse1" class="collapse dropdown-main-wp" aria-labelledby="menu_heading1" data-parent="#a_menumain_wp">
                         <div class="dropdown-main accordion" id="a_menumain">
                            <div class="s_item_row-main">
                              <div class="s_item_row">
                                 <div class="s_item">
                                   <div class="item-header" id="sm_heading1">
                                      <h4 class="sb_menu-title ">
                                          <span> App Development </span>
                                          <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                                            data-target="#s_collapse1" aria-expanded="false" aria-controls="s_collapse1">
                                            <i class="fa fa-angle-down"></i>
                                          </button>
                                      </h4>
                                   </div>
                                   <div id="s_collapse1" class="collapse sub-menu-main" aria-labelledby="sm_heading1"
                                      data-parent="#a_menumain">
                                      <ul class="sub-menu">
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Native App Development</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Ios App Development</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Android App Development</a></li>
                                          <li class="sub-menu-link "><a href="javascript:void(0)" class="contact-us-click">Hybrid App Development</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Flutter App Development</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">React Native App Development</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">App Maintenance</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">3rd Party API Integration</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Apple App Store Submission</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Google Play Store Submission</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Manual Testing</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Maintenance And Support</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Android Wear App Development</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Apple Watch App Development</a></li>
                                      </ul>
                                   </div>
                                 </div>
                              </div>
                              <div class="s_item_row">
                                 <div class="s_item">
                                   <div class="item-header" id="sm_heading2">
                                      <h4 class="sb_menu-title ">
                                          <span>Web Development</span>
                                          <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                                            data-target="#s_collapse2" aria-expanded="false" aria-controls="s_collapse2">
                                            <i class="fa fa-angle-down"></i>
                                          </button>
                                      </h4>
                                   </div>
                                   <div id="s_collapse2" class="collapse sub-menu-main" aria-labelledby="sm_heading2"
                                      data-parent="#a_menumain">
                                      <ul class="sub-menu">
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Web Development</a></li> 
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Front-End Development Html</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Back-End Development Php</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Mysql Database</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">AWS - Amazon Web Services </a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Configuration And Hosting</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">3rd Party API Integration</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Testing</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Maintenance And Support</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Source Code Review</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">React.Js Developement</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Laravel Developement</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Node.Js Developement</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Codeigniter Developement</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Wordpress Developement</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Woocommerce Developement</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Magento Developement</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Html5 Development</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Google Analytics</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Google Firebase</a></li>

                                      </ul>
                                   </div>
                                 </div>
                              </div>
                              <div class="s_item_row">
                                 <div class="s_item">
                                    <div class="item-header" id="sm_heading4">
                                      <h4 class="sb_menu-title ">
                                          <span>Design</span>
                                          <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                                            data-target="#s_collapse4" aria-expanded="false" aria-controls="s_collapse4">
                                            <i class="fa fa-angle-down"></i>
                                          </button>
                                      </h4>
                                    </div>
                                    <div id="s_collapse4" class="collapse sub-menu-main" aria-labelledby="sm_heading4"
                                      data-parent="#a_menumain">
                                       <ul class="sub-menu">
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">UI/UX Design</a></li> 
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Prototype</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Investor Pitchdeck</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">App Branding</a></li>
                                       </ul>
                                    </div>
                                 </div>
                                 <div class="s_item">
                                    <div class="item-header" id="sm_heading5">
                                      <h4 class="sb_menu-title ">
                                          <span>Consultation</span>
                                          <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                                            data-target="#s_collapse5" aria-expanded="false" aria-controls="s_collapse5">
                                            <i class="fa fa-angle-down"></i>
                                          </button>
                                      </h4>
                                    </div>
                                    <div id="s_collapse5" class="collapse sub-menu-main" aria-labelledby="sm_heading5"
                                      data-parent="#a_menumain">
                                       <ul class="sub-menu">
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Comprehensive Consultation</a></li> 
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Technical Solution</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Blueprint</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Project Scoping</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Manual Testing</a></li>
                                       </ul>
                                    </div>
                                 </div>
                                 <div class="s_item">
                                    <div class="item-header" id="sm_heading6">
                                      <h4 class="sb_menu-title ">
                                          <span>Hosting</span>
                                          <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                                            data-target="#s_collapse6" aria-expanded="false" aria-controls="s_collapse6">
                                            <i class="fa fa-angle-down"></i>
                                          </button>
                                      </h4>
                                    </div>
                                    <div id="s_collapse6" class="collapse sub-menu-main" aria-labelledby="sm_heading6"
                                      data-parent="#a_menumain">
                                       <ul class="sub-menu">
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">AWS Deployment</a></li> 
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Cloud Hosting</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Email Hosting</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">SSL</a></li>
                                       </ul>
                                    </div>
                                 </div>
                              </div>
                              <div class="s_item_row">
                                 <div class="s_item">
                                    <div class="item-header" id="sm_heading7">
                                      <h4 class="sb_menu-title ">
                                          <span>Payment Integration</span>
                                          <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                                            data-target="#s_collapse7" aria-expanded="false" aria-controls="s_collapse7">
                                            <i class="fa fa-angle-down"></i>
                                          </button>
                                      </h4>
                                    </div>
                                    <div id="s_collapse7" class="collapse sub-menu-main" aria-labelledby="sm_heading7"
                                      data-parent="#a_menumain">
                                       <ul class="sub-menu">
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Stripe</a></li> 
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Split</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Paypal</a></li>
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">Basiq</a></li>
                                       </ul>
                                    </div>
                                 </div>
                                 <div class="s_item">
                                    <div class="item-header" id="sm_heading8">
                                      <h4 class="sb_menu-title ">
                                          <span>Thirdparty Integration</span>
                                          <button class="dropdown-click collapsed" type="button" data-toggle="collapse"
                                            data-target="#s_collapse8" aria-expanded="false" aria-controls="s_collapse8">
                                            <i class="fa fa-angle-down"></i>
                                          </button>
                                      </h4>
                                    </div>
                                    <div id="s_collapse8" class="collapse sub-menu-main" aria-labelledby="sm_heading8"
                                      data-parent="#a_menumain">
                                       <ul class="sub-menu">
                                          <li class="sub-menu-link"><a href="javascript:void(0)" class="contact-us-click">SerivceM8</a></li> 
                                       </ul>
                                    </div>
                                 </div>
                              </div>
                            </div>
                         </div>
                      </div>
                    </li>

                    <li class="nav-item <?php echo ($slug == 'app-development-process-mobile-app-development-company-brisbane-australia')?'active':''; ?>">
                      <a href="<?php echo esc_url( home_url( 'app-development-process-mobile-app-development-company-brisbane-australia/' ) ); ?>">Process</a>
                    </li>
                    
                </ul>
              <div class="header-btn">
              <!-- <a href="javascript:void(0)" class="btn contact-us-click" oncontextmenu="return false;">Contact Us </a> -->
              <button class="btn cta contact-us-click header-btn" oncontextmenu="return false;" type="button">Contact Us</button>
              </div>

              <div class="hedear-call-us">
                <ul>
                  <li><a href="tel:1300 699 571" class="btn">1300 699 571</a></li>
                  <li><button class="btn black-btn contact-us-click" oncontextmenu="return false;" type="button">Free consultation</button></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>

<!-- ====== /contact Section BOC ====== --> 
<section id="contact-us">
  <div class="contact-us-main">
    <div class="contact-us black-bg"> 
      <div class="contact-us-inner">
        <div class="form-main">
          <div class="form-title">
            <div class="form-title-inner">
            <h2 class="white-color-text">Contact Us</h2>
            <p class="white-color-text">If you have made it this far, you are here with a reason. You need our help! We are super friendly and genuinely care to help you succeed.</p>
            <h6 class="white-color-text font-we-rg"><span class="orange-color-text">Enquire today</span> to receive a FREE consultation with an App Guru.</h6>
            </div>
          </div>

          <?php echo do_shortcode('[contact-form-7 id="238" title="Contact Form"]'); ?>

          <div class="email-link-main">
            <h6 class="white-color-text">Get in Touch</h6>
            <a href="mailto:<?php echo the_field('website_email','option');?>">info [at] appgurus.com.au</a>
          </div>
        </div>
        <div class="contact-us-close">
        <a href="javascript:void(0)"><span class="close-icon"></span><span class="close-icon"></span></a>
        </div>
      </div>
    </div>
  </div>      
</section>
<!-- ====== /contact Section EOC ====== --> 
</header>

<div class="call-us-main">
  <div class="call-us-inner">
    <ul>
      <li class="call-us-text">Call Us</li>
      <li><a href="tel:1300 699 571" class="btn">1300 699 571</a></li>
      <li><button class="btn black-btn contact-us-click" oncontextmenu="return false;" type="button">Free consultation</button></li>
    </ul>
  </div>
</div>
<?php } ?>