<?php
/**
* Header file for the Twenty Twenty WordPress default theme.
*
* @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
*
* @package WordPress
* @subpackage Twenty_Twenty
* @since Twenty Twenty 1.0
*/
?>
<!DOCTYPE html>

<html class="no-js" <?php language_attributes(); ?>>

<head>

  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-7CPB7RZ1MZ"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-7CPB7RZ1MZ');
  </script>
  <script type="text/javascript">
    var ajaxurl = "<?php echo admin_url('admin-ajax.php'); ?>";
  </script>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="google-site-verification" content="5Au7RwZpnetIiB9AJIrDhPnZcLsvS2uieKOr4_r5kAs" />
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<?php wp_head(); ?>
<!-- ================ /GOOGLE FONT EOC =================== -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<!-- ================ /GOOGLE FONT EOC =================== -->

<!-- =================== /WEB CSS BOC ==================== -->
<link rel="stylesheet" type="text/css" href="<?php echo get_template_directory_uri(); ?>/assets/css/consultation/bootstrap-5.0.2/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo get_template_directory_uri(); ?>/assets/css/consultation/consultationstyle.css">
<link rel="stylesheet" type="text/css" href="<?php echo get_template_directory_uri(); ?>/assets/css/consultation/media.css">
<script src="https://www.google.com/recaptcha/api.js?render=6LdT43smAAAAADOmCvzIAYrRmXPbuiBDsEB9U_xb"></script>
<!-- =================== /WEB CSS EOC ==================== -->

<style type="text/css">
  .show_hide {display:none; }
</style>

</head>

<body <?php body_class(); ?>>
