–ûÀY<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:3497;s:11:"post_author";s:1:"1";s:9:"post_date";s:19:"2014-08-22 20:23:03";s:13:"post_date_gmt";s:19:"2014-08-22 20:23:03";s:12:"post_content";s:23292:"[vc_row][vc_column][mk_fancy_title color="#333333" size="24" font_weight="bold" txt_transform="uppercase" letter_spacing="2" margin_top="90" margin_bottom="0" align="center"]7 icon boxÂ styles[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="25" thickness="3" margin_top="15" margin_bottom="35"][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][vc_column_text disable_pattern="false" align="center"]<span style="color: #6e6e6e; font-size: 16px;">This shortcode comes handy for those who want to have more customised look. You can play around massive options and unlimited colors and sizes.</span>[/vc_column_text][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="100" margin_bottom="50"][/vc_column][/vc_row][vc_row][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-umbrella" icon_color="#333333" icon_hover_color="#ffffff" icon_hover_background_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-scissor" icon_color="#333333" icon_hover_color="#ffffff" icon_hover_background_color="#5b98db" title="DEEPLY CUSTOMISABLE " title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-paper-plane" icon_color="#333333" icon_hover_color="#ffffff" icon_hover_background_color="#3edbd9" title="SMOOTH AND FLUENT " title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-like" icon_color="#333333" icon_hover_color="#ffffff" icon_hover_background_color="#7365b2" title="LIKED BY THOUSANDS" title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-umbrella" icon_color="#f97352" icon_background_color="#f0f0f0" icon_hover_color="#ffffff" icon_hover_background_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-scissor" icon_color="#f97352" icon_background_color="#f0f0f0" icon_hover_color="#ffffff" icon_hover_background_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-paper-plane" icon_color="#f97352" icon_background_color="#f0f0f0" icon_hover_color="#ffffff" icon_hover_background_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-scissor" icon_color="#f97352" icon_background_color="#f0f0f0" icon_hover_color="#ffffff" icon_hover_background_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#333333" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-umbrella" icon_color="#f97352" icon_border_color="#d9d9d9" icon_hover_color="#f97352" icon_hover_border_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#f97352" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-scissor" icon_color="#f97352" icon_border_color="#d9d9d9" icon_hover_color="#f97352" icon_hover_border_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#f97352" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-paper-plane" icon_color="#f97352" icon_border_color="#d9d9d9" icon_hover_color="#f97352" icon_hover_border_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#f97352" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/4"][mk_icon_box2 icon_size="48" icon="mk-li-like" icon_color="#f97352" icon_border_color="#d9d9d9" icon_hover_color="#f97352" icon_hover_border_color="#f97352" title="OUTSTANDING SUPPORT" title_size="14" title_weight="bold" title_color="#f97352" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column][mk_fancy_title color="#333333" size="16" font_weight="bold" txt_transform="uppercase" letter_spacing="1" margin_top="40" margin_bottom="0" align="center"]UPLOAD YOUR OWN ICON IMAGES[/mk_fancy_title][mk_divider style="thin_solid" divider_width="custom_width" custom_width="30" thickness="3" margin_top="10" margin_bottom="55"][/vc_column][/vc_row][vc_row][vc_column width="1/3"][mk_icon_box2 icon_type="image" icon_size="128" icon_image="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/icon-03.png" title="RESEARCH &amp; STUDY" title_size="16" title_weight="bold" title_color="#f97352" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/3"][mk_icon_box2 icon_type="image" icon_size="128" icon_image="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/icon-01.png" title="ADVANCED MAP" title_size="16" title_weight="bold" title_color="#f97352" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][vc_column width="1/3"][mk_icon_box2 icon_type="image" icon_size="128" icon_image="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/icon-02.png" title="AMAZING PHOTO GALLERY" title_size="16" title_weight="bold" title_color="#f97352" title_top_padding="30" title_bottom_padding="15" description_color="#545454" description="Cras dapibus arcu a neque laoreet condimentum. In in rhoncus leo. Sed mattis feugiat odio, sit amet pretium nisl egestas non. Suspendisse dui velit"]
<p style="color: #999;">Cras tristique turpis justo, eu consequat sem adipiscing ut. Donec posuere bibendum metus. Quisque gravida luctus volutpat. Mauris interdum.</p>

[/mk_icon_box2][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/3"][mk_icon_box icon="moon-bag-2" title="Online shopping" font_weight="inhert" read_more_txt="Read more" read_more_url="#" style="simple_ultimate" icon_color="#0bb697" txt_color="#333333" box_blur="false" width="1/1" el_position="first"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget sit amet enim.

[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="moon-stack" title="Amazing slideshows" read_more_txt="Read more" read_more_url="#" style="simple_ultimate" icon_color="#0bb697" box_blur="false" width="1/1"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget sit amet enim.[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="moon-lamp-2" title="Innovative features" font_weight="inhert" read_more_txt="Read more" read_more_url="#" style="simple_ultimate" icon_color="#0bb697" box_blur="false" width="1/1" el_position="last"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget sit amet enim.

[/mk_icon_box][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/4"][mk_icon_box icon="moon-cube4" title="Powerful admin" text_size="14" font_weight="inhert" read_more_txt="Find out" icon_color="#f56a5f" icon_circle_color="#0bb697" box_blur="false" width="1/1" el_position="first"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/4"][mk_icon_box icon="moon-home-12" title="Homepage layouts" text_size="14" font_weight="inhert" read_more_txt="Find out" read_more_url="#" icon_color="#f56a5f" icon_circle_color="#0bb697" box_blur="false" width="1/1"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/4"][mk_icon_box icon="moon-chart" title="Built-in charts" text_size="14" font_weight="inhert" read_more_txt="Find out" read_more_url="#" icon_color="#f56a5f" icon_circle_color="#0bb697" box_blur="false" width="1/1"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/4"][mk_icon_box icon="moon-screen-3" title="Fluid layouts" text_size="14" font_weight="inhert" read_more_txt="Find out" read_more_url="#" icon_color="#f56a5f" icon_circle_color="#0bb697" box_blur="false" width="1/1" el_position="last"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/3"][mk_icon_box icon="moon-mouse-2" title="Easy to use" font_weight="inhert" read_more_txt="Find out" read_more_url="#" circled="true" icon_color="#89d9d1" icon_circle_color="#164f73" icon_circle_border_color="#164f73" box_blur="false" width="1/1" el_position="first"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="moon-pushpin" title="Map integration" text_size="14" font_weight="inhert" read_more_txt="Find out" read_more_url="#" circled="true" icon_color="#beae54" icon_circle_color="#f2ebc4" icon_circle_border_color="#cfbf64" box_blur="false" width="1/1"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="moon-mobile-2" title="Responsive layout" text_size="14" font_weight="inhert" read_more_txt="Find out" read_more_url="#" circled="true" icon_color="#ffffff" icon_circle_color="#f28379" icon_circle_border_color="#f28379" box_blur="false" width="1/1" el_position="last"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/3" el_position="first"][mk_padding_divider size="91" width="1/1" el_position="first last"][mk_icon_box icon="moon-crown" title="Premium quality icons" font_weight="inhert" read_more_txt="Find out" read_more_url="#" style="simple_ultimate" icon_size="medium" icon_location="top" icon_color="#c5af55" box_blur="false" width="1/1" el_position="first last"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_padding_divider size="70" width="1/1" el_position="first last"][mk_icon_box icon="moon-earth" title="Multi-language support" text_size="20" font_weight="normal" read_more_txt="Find out" read_more_url="#" style="simple_ultimate" icon_size="large" icon_location="top" icon_color="#78c57e" box_blur="false" width="1/1" el_position="first last"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="moon-alarm" title="Fast loading pages" text_size="22" font_weight="300" read_more_txt="Find out" read_more_url="#" style="simple_ultimate" icon_size="x-large" icon_location="top" icon_color="#c25151" box_blur="false" width="1/1" el_position="last"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/3"][mk_icon_box icon="moon-pen-2" title="Great blog features" font_weight="inhert" read_more_txt="Find out" read_more_url="#" style="boxed" icon_location="top" icon_color="#c2eee7" icon_circle_color="#00b89a" icon_circle_border_color="#00b89a" box_blur="false" width="1/1" el_position="first"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="moon-lab" title="Advanced framework behind" font_weight="inhert" read_more_txt="Find out" read_more_url="#" style="boxed" icon_location="top" icon_color="#c2eee7" icon_circle_color="#00b89a" icon_circle_border_color="#00b89a" box_blur="false" width="1/1"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="moon-paint-format-2" title="Extensive alternate styles" font_weight="inhert" read_more_txt="Find out" read_more_url="#" style="boxed" icon_location="top" icon_color="#c2eee7" icon_circle_color="#00b89a" icon_circle_border_color="#00b89a" box_blur="false" width="1/1" el_position="last"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget.

[/mk_icon_box][/vc_column][/vc_row][vc_row fullwidth="true" padding="0"][vc_column][mk_divider style="thin_solid" margin_top="60" margin_bottom="70"][/vc_column][/vc_row][vc_row][vc_column width="1/2"][mk_icon_box icon="moon-glasses-3" title="Retina display ready" font_weight="inhert" read_more_txt="Find out" read_more_url="#" style="boxed" icon_color="#ffffff" icon_circle_color="#c16f60" icon_circle_border_color="#c16f60" box_blur="false" width="1/1" el_position="first"]

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget. Quisque at tortor a libero posuere laoreet vitae sed arcu curabitur consequat nunc

[/mk_icon_box][/vc_column][vc_column width="1/2"][mk_icon_box icon="moon-bullhorn" title="Innovative callout boxes" font_weight="bold" read_more_txt="Find out" read_more_url="#" style="boxed" icon_color="#ffffff" icon_circle_color="#c16f60" icon_circle_border_color="#c16f60" box_blur="false" width="1/1" el_position="last"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum. Sed in nisi non metus fringilla pulvinar eget. Quisque at tortor a libero posuere laoreet vitae sed arcu curabitur consequat nunc[/mk_icon_box][/vc_column][/vc_row][vc_row][vc_column][vc_empty_space height="60px"][/vc_column][/vc_row][mk_page_section bg_image="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/08/employee-blur-box.jpg" bg_position="center center" bg_repeat="repeat-y" bg_stretch="true" padding_top="100" padding_bottom="100" sidebar="sidebar-1" first_page="false" last_page="false"][vc_column width="1/3"][mk_icon_box icon="mk-li-cup" title="Stability and reliability" font_weight="bold" read_more_txt="Find out" style="boxed" icon_location="top" icon_color="#dcb784" icon_circle_color="#202a2e" title_color="#444444" txt_color="#444444" margin="0" box_blur="true"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum sed in nisi.[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="mk-li-pill" title="Great customer support" font_weight="bold" read_more_txt="Find out" style="boxed" icon_location="top" icon_color="#dcb784" icon_circle_color="#202a2e" title_color="#444444" txt_color="#444444" margin="0" box_blur="true"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum sed in nisi.[/mk_icon_box][/vc_column][vc_column width="1/3"][mk_icon_box icon="mk-li-sun" title="Premium quality icons" font_weight="bold" read_more_txt="Find out" style="boxed" icon_location="top" icon_color="#dcb784" icon_circle_color="#202a2e" title_color="#444444" txt_color="#444444" margin="0" box_blur="true"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget porta mi, sit amet volutpat ipsum sed in nisi.[/mk_icon_box][/vc_column][/mk_page_section]";s:10:"post_title";s:8:"Icon box";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:4:"open";s:11:"ping_status";s:4:"open";s:13:"post_password";s:0:"";s:9:"post_name";s:8:"icon-box";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2014-08-22 20:23:03";s:17:"post_modified_gmt";s:19:"2014-08-22 20:23:03";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:395;s:4:"guid";s:47:"http://demos.artbees.net/jupiter5/?page_id=3497";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}