…ýÀY<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":23:{s:2:"ID";s:4:"9676";s:11:"post_author";s:1:"1";s:9:"post_date";s:19:"2016-04-18 15:05:52";s:13:"post_date_gmt";s:19:"2016-04-18 15:05:52";s:12:"post_content";s:2765:"[mk_page_section bg_image="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/09/template-header-bg.jpg" attachment="fixed" bg_position="center center" bg_repeat="no-repeat" bg_stretch="true" enable_3d="true" speed_factor="0.5" video_color_mask="#000000" video_opacity="0.3" padding_top="280" padding_bottom="0" sidebar="sidebar-1"][vc_column css=".vc_custom_1410594337284{background-position: 0 0 !important;background-repeat: no-repeat !important;}"][mk_fancy_title tag_name="h3" color="#ffffff" size="44" font_weight="bold" txt_transform="uppercase" letter_spacing="6" margin_bottom="40" font_family="none" align="center" animation="fade-in"]Bright as the moons of Jupiter
Enduring as its myths[/mk_fancy_title][mk_fancy_title tag_name="h5" color="#ffffff" size="16" font_weight="normal" txt_transform="uppercase" letter_spacing="2" margin_bottom="115" font_family="none" align="center" animation="fade-in"]

Introducing Jupiter Templates

[/mk_fancy_title][mk_image src="http://demos.artbees.net/jupiter5/wp-content/uploads/2016/04/templates-snapshot-header.png" image_size="full" group="_general" align="center" margin_bottom="0" crop="false"][/vc_column][/mk_page_section][mk_page_section bg_color="#f2f2f2" top_shape_color="#ffffff" has_bottom_shape_divider="true" bottom_shape_style="folded-bottom" bottom_shape_size="small" bottom_shape_color="#ededed" sidebar="sidebar-1"][vc_column][mk_padding_divider size="120"][mk_image src="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/09/template-title.png" image_width="340" image_height="42" group="_general" align="center" crop="false"][mk_padding_divider size="75"][mk_image src="http://demos.artbees.net/jupiter5/wp-content/uploads/2014/09/template-select-process-01.gif" image_width="1496" image_height="1337" group="_general" align="center" crop="false"][mk_fancy_title size="20" font_weight="bold" txt_transform="none" letter_spacing="1" margin_top="60" font_family="none" align="center"]

Once you press "Install" ...

[/mk_fancy_title][vc_column_text align="center"]All theme settings, widgets, post and page layouts
will be installed on your server automatically and instantly.[/vc_column_text][mk_padding_divider][/vc_column][/mk_page_section][vc_row][vc_column][mk_fancy_title tag_name="h4" color="#000000" size="28" txt_transform="none" letter_spacing="2" margin_top="120" margin_bottom="80" font_family="none" align="center"]Take your pick[/mk_fancy_title][/vc_column][/vc_row][vc_row][vc_column][mk_portfolio style="grid" hover_scenarios="fadebox" grid_spacing="16" image_size="full" zoom_icon="false" count="-1" sortable="false" pagination="false" target="_blank" categories="templates"][/vc_column][/vc_row][vc_row][vc_column][mk_padding_divider size="120"][/vc_column][/vc_row]";s:10:"post_title";s:9:"Templates";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:6:"closed";s:11:"ping_status";s:6:"closed";s:13:"post_password";s:0:"";s:9:"post_name";s:9:"templates";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2016-04-18 15:05:52";s:17:"post_modified_gmt";s:19:"2016-04-18 15:05:52";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";s:1:"0";s:4:"guid";s:47:"http://demos.artbees.net/jupiter5/?page_id=9545";s:10:"menu_order";s:1:"0";s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";}}